[VIDEO-3086] Configure gst-plugins-rs source, ref
blinemedical/cerbero pull request #18
Opened 2024-10-24 20:47 UTC by btgoodwin

Updated the github action to add `recipes_remotes` and `recipes_commits` into the configuration file, pointing `gst-plugins-rs` at our repository.

**NOTE:** DO NOT MERGE until we have a tag with these two changes merged and the github action file is updated to that reference accordingly.

1. blinemedical/gst-plugins-rs#2
2. blinemedical/gst-plugins-rs#3

2024-10-25 15:47 UTC, btgoodwin commented
I'm stumped.  Earlier I let it run with a different existing tag and it was fine.  Now it's not with the new tag.  Their readme says "branch"...which won't be great; the variable is called commits after all.

2024-10-25 17:29 UTC, btgoodwin commented
Look'n good.  It made it past the `fetch` step @jawilson.  Please let me know if this is implemented how you would have preferred.  I used a pair of input variables to tie this back.  The one for the ref can either be the `lldc/<branch name>` or a tag that's unique to our repository, as is currently set in this PR.

2024-10-28 15:17 UTC, jawilson requested changes
We'll need to also update the [`config-hash`](https://github.com/blinemedical/cerbero/blob/41220ad680bb64cafbc6840d5509b34105e6566a/.github/actions/build-gstreamer-for-windows/action.yml#L224-L225) calculation. I'd suggest something simple like:
```
config_hash=$(echo "${CERBERO_ARGS}${{ inputs.config }}${GST_PLUGINS_RS_SOURCE}${GST_PLUGINS_RS_REF}" | sha256sum | cut -d' ' -f1)
```

2024-10-28 15:17 UTC, jawilson commented on .github/actions/build-gstreamer-for-windows/action.yml
> +    default: '0.12.9-lldc.1'
I'd prefer to leave these blank and pass them in from the calling side.
```suggestion
  gst-plugins-rs-repo:
    description: 'Repository to use for gst-plugins-rs'
    required: false
  gst-plugins-rs-ref:
    description: 'Ref/tag to use for gst-plugins-rs'
    required: false
```

2024-10-28 15:17 UTC, jawilson commented on .github/actions/build-gstreamer-for-windows/action.yml
> +        echo "recipes_commits = {'gst-plugins-rs': '${GST_PLUGINS_RS_REF}'}" >> localconf.cbc
To support allowing these to be blank:
```suggestion
        # Handle custom gst-plugins-rs provider
        if [ -n "${GST_PLUGINS_RS_SOURCE}" ] && [ -n "${GST_PLUGINS_RS_REF}" ]; then
          echo "recipes_remotes = {'gst-plugins-rs': {'patched': '${GST_PLUGINS_RS_SOURCE}'}}" >> localconf.cbc
          echo "recipes_commits = {'gst-plugins-rs': '${GST_PLUGINS_RS_REF}'}" >> localconf.cbc
        fi
```

2024-10-28 17:17 UTC, jawilson approved these changes
LGTM assuming the build passes.

2024-10-28 18:42 UTC, btgoodwin commented
@jawilson Well, it's through the wickets but I can't merge to the branch because it's protected.  I assume you have permission?

2024-10-28 19:31 UTC, jawilson commented
> @jawilson Well, it's through the wickets but I can't merge to the branch because it's protected. I assume you have permission?

Got a little carried away with the branch protection rulesets. I couldn't merge either. Updated and good to merge now.

2024-10-28 19:31 UTC, merged